### ISSUE TITLE
'cluster_analysis' workbook

### ISSUE THREAD

**Issue by GlorianY** [brandomr/document_cluster#13]
Hi Brandon,

Great work on http://brandonrose.org/clustering!

But, where can I find the cluster analysis full workbook? I want to look what is the structure of the "synopses" list. Is it a regular 2D Python list?

Cheers,
Glorian

**Comment by brandomr** [comment]
Thanks! Here's the workbook: [cluster_analysis.ipynb](https://github.com/brandomr/document_cluster/blob/master/cluster_analysis.ipynb) and here is the [film synopses data](https://github.com/brandomr/document_cluster/blob/master/synopses_list_wiki.txt). I just split that file on `BREAKS HERE` (some text I inserted in the scraping process) in order to create a list (array) of strings such as:

```
synopses  = [ 'film synopses 1',
             'film synopsis 2',
             'film synopsis 3' ]
```
